AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "lib/xmi/uml13/**/*.rb"
    - "vendor/bundle/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false
