# frozen_string_literal: true

module Xmi
  module Uml
    autoload :Base, "xmi/uml/base"
    autoload :AnnotatedElement, "xmi/uml/annotated_element"
    autoload :Type, "xmi/uml/type"
    autoload :MemberEnd, "xmi/uml/member_end"
    autoload :DefaultValue, "xmi/uml/default_value"
    autoload :UpperValue, "xmi/uml/upper_value"
    autoload :LowerValue, "xmi/uml/lower_value"
    autoload :ValueSpecification, "xmi/uml/value_specification"
    autoload :LiteralString, "xmi/uml/literal_string"
    autoload :LiteralInteger, "xmi/uml/literal_integer"
    autoload :LiteralBoolean, "xmi/uml/literal_boolean"
    autoload :LiteralUnlimitedNatural, "xmi/uml/literal_unlimited_natural"
    autoload :LiteralNull, "xmi/uml/literal_null"
    autoload :OpaqueExpression, "xmi/uml/opaque_expression"
    autoload :Slot, "xmi/uml/slot"
    autoload :InterfaceRealization, "xmi/uml/interface_realization"
    autoload :OwnedEnd, "xmi/uml/owned_end"
    autoload :OwnedLiteral, "xmi/uml/owned_literal"
    autoload :OwnedAttribute, "xmi/uml/owned_attribute"
    autoload :Specification, "xmi/uml/specification"
    autoload :OwnedParameter, "xmi/uml/owned_parameter"
    autoload :Precondition, "xmi/uml/precondition"
    autoload :OwnedOperation, "xmi/uml/owned_operation"
    autoload :OwnedComment, "xmi/uml/owned_comment"
    autoload :AssociationGeneralization, "xmi/uml/association_generalization"
    autoload :PackagedElement, "xmi/uml/packaged_element"
    autoload :UmlClass, "xmi/uml/uml_class"
    autoload :Association, "xmi/uml/association"
    autoload :Interface, "xmi/uml/interface"
    autoload :InstanceSpecification, "xmi/uml/instance_specification"
    autoload :DataType, "xmi/uml/data_type"
    autoload :PrimitiveType, "xmi/uml/primitive_type"
    autoload :Enumeration, "xmi/uml/enumeration"
    autoload :Package, "xmi/uml/package"
    autoload :Realization, "xmi/uml/realization"
    autoload :Dependency, "xmi/uml/dependency"
    autoload :Signal, "xmi/uml/signal"
    autoload :AssociationClass, "xmi/uml/association_class"
    autoload :Extension, "xmi/uml/extension"
    autoload :Stereotype, "xmi/uml/stereotype"
    autoload :Usage, "xmi/uml/usage"
    autoload :Component, "xmi/uml/component"
    autoload :Bounds, "xmi/uml/bounds"
    autoload :Waypoint, "xmi/uml/waypoint"
    autoload :OwnedElement, "xmi/uml/owned_element"
    autoload :Diagram, "xmi/uml/diagram"
    autoload :ProfileApplicationAppliedProfile,
             "xmi/uml/profile_application_applied_profile"
    autoload :ProfileApplication, "xmi/uml/profile_application"
    autoload :ImportedPackage, "xmi/uml/imported_package"
    autoload :PackageImport, "xmi/uml/package_import"
    autoload :UmlModel, "xmi/uml/uml_model"
    autoload :Profile, "xmi/uml/profile"
  end
end
